### ISSUE TITLE
Refactor and rearrange templates

### ISSUE THREAD

**Issue by ryanvarick** [dsa-ntc/actionkit-template-renderer#21]
Goal is to to make things easier to manage:

* Move DSA templates into their own folder
* Make first-class templates clearer so they are not changed
* Extract reusable bits like mailing address into separate templates 

@emiliadecaudin will take this.

**Comment by emiliadecaudin** [comment]
Refactored custom templates to have the prefix `custom_` instead of being in their own folder because ActionKit does not support folders for templates. A number of custom templates will be revealed to not be necessary when we reconcile existing templates with the latest version of ActionKit's default templates.

Next step will be to break up membership_style_redesign into components.

**Comment by emiliadecaudin** [comment]
Primary membership field controls have been extracted and separated out!
